version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      extra_requirements:
        - docs
      path: .

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false
