# This workflow will install Python dependencies, run tests, run linting, and test building docs
name: Codestyle and Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.10]

steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pip setuptools wheel --upgrade
        python -m pip install -e '.[dev]'
    - name: Lint with Black
      run: |
        black --check --diff roentgen
    - name: flake8
      run: |
        flake8 --count roentgen
    - name: isort
      run: |
        isort roentgen -c
